/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telaCadastros;

import cadastros.ConfigDefault;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author luiz.barcellos
 */
public class Configuracoes extends javax.swing.JInternalFrame {

    ConfigDefault cd = new ConfigDefault();

    private Double inss_aliq_cooperado;
    private Double inss_aliq_patronal_cooperado;
    private Double inss_aliq_patronal_terceiro;
    private Double inss_aliq_terceiro;
    private Double inss_bc_cooperado;
    private Double inss_bc_terceiro;
    private boolean inss_tab_local;
    private boolean irrf_tab_local;
    private Double irrf_bc_cooperado;
    private Double irrf_bc_terceiro;
    private boolean lanca_fin;
    private boolean lanca_folha;
    private boolean margem_variavel;
    private Double margem_cooperado;
    private Double margem_terceiro;
    private Double coop_terceiros_aliq;
    private Double terc_terceiros_aliq;
    private String cta_cooperado;
    private String cta_terceiro;
    private String cta_outras_despesas;
    private String cta_inss;
    private String cta_irrf;
    private String ult_integ_fin;
    private boolean considera_pedagio;
    
    DateFormat df = new SimpleDateFormat("dd' de 'MMMM' de 'yyyy', às 'HH:mm:ss");

    /**
     * Creates new form Configuracoes
     */
    public Configuracoes() {
        initComponents();
        buscaDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpMargemTerc = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCbMargemVar = new javax.swing.JCheckBox();
        jSpMargemCoop = new javax.swing.JSpinner();
        jCbPedagio = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpInssTerc_Coop = new javax.swing.JSpinner();
        jSpInssPatronal_Coop = new javax.swing.JSpinner();
        jSpInssAliq_Coop = new javax.swing.JSpinner();
        jSpInssBase_Coop = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSpINSSTerc_Terc = new javax.swing.JSpinner();
        jSpINSSPatronal_Terc = new javax.swing.JSpinner();
        jSpINSSProprio_Terc = new javax.swing.JSpinner();
        jSpBaseINSS_Terc = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jSpBase_IRRFTerc = new javax.swing.JSpinner();
        jLabel33 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jSpBaseIRRF_Coop = new javax.swing.JSpinner();
        jLabel41 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCbInteg_Financ = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTxtCtaCoop = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTxtCtaTerc = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTxtCtaINSS = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTxtCtaIRRF = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTxtCtaOutras = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTxtUltRpaInteg = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jCbInteg_Folha = new javax.swing.JCheckBox();
        jCbTabINSS = new javax.swing.JCheckBox();
        jCbTabIRRF = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jTxtSinc = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTxtUser = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jBtnGravar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setTitle("Configurações Gerais");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Margens"));

        jLabel1.setText("Cooperado");

        jSpMargemTerc.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jSpMargemTerc.setEditor(new javax.swing.JSpinner.NumberEditor(jSpMargemTerc, "0.00"));

        jLabel2.setText("Terceiro");

        jLabel3.setText("%");

        jLabel4.setText("%");

        jCbMargemVar.setText("Margem Variável");
        jCbMargemVar.setToolTipText("Marcar esta opção fará com que o RPA solicite o valor da tonelada a cada Conhecimento de Frete informado.");

        jSpMargemCoop.setModel(new javax.swing.SpinnerNumberModel());
        jSpMargemCoop.setEditor(new javax.swing.JSpinner.NumberEditor(jSpMargemCoop, "0.00"));

        jCbPedagio.setText("Considera Pedágio");
        jCbPedagio.setToolTipText("Marcar esta opção fará com que o RPA solicite o valor da tonelada a cada Conhecimento de Frete informado.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpMargemCoop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpMargemTerc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jCbMargemVar)
                        .addGap(18, 18, 18)
                        .addComponent(jCbPedagio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jCbMargemVar)
                    .addComponent(jSpMargemCoop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbPedagio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpMargemTerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("INSS Cooperado"));

        jLabel5.setText("Base de Cálculo");

        jLabel6.setText("Alíquota Própria");

        jLabel7.setText("Alíquota Patronal");

        jLabel8.setText("Alíquota SEST / SENAT");

        jSpInssTerc_Coop.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jSpInssTerc_Coop.setEditor(new javax.swing.JSpinner.NumberEditor(jSpInssTerc_Coop, "0.00"));

        jSpInssPatronal_Coop.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jSpInssPatronal_Coop.setEditor(new javax.swing.JSpinner.NumberEditor(jSpInssPatronal_Coop, "0.00"));

        jSpInssAliq_Coop.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jSpInssAliq_Coop.setEditor(new javax.swing.JSpinner.NumberEditor(jSpInssAliq_Coop, "0.00"));

        jSpInssBase_Coop.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jSpInssBase_Coop.setEditor(new javax.swing.JSpinner.NumberEditor(jSpInssBase_Coop, "0.00"));

        jLabel9.setText("%");

        jLabel10.setText("%");

        jLabel11.setText("%");

        jLabel12.setText("%");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jSpInssBase_Coop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jSpInssAliq_Coop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jSpInssPatronal_Coop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jSpInssTerc_Coop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpInssBase_Coop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpInssAliq_Coop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpInssPatronal_Coop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSpInssTerc_Coop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("INSS Terceiros"));

        jLabel13.setText("Base de Cálculo");

        jLabel14.setText("Alíquota Própria");

        jLabel15.setText("Alíquota Patronal");

        jLabel16.setText("Alíquota SEST / SENAT");

        jSpINSSTerc_Terc.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jSpINSSTerc_Terc.setEditor(new javax.swing.JSpinner.NumberEditor(jSpINSSTerc_Terc, "0.00"));

        jSpINSSPatronal_Terc.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jSpINSSPatronal_Terc.setEditor(new javax.swing.JSpinner.NumberEditor(jSpINSSPatronal_Terc, "0.00"));

        jSpINSSProprio_Terc.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jSpINSSProprio_Terc.setEditor(new javax.swing.JSpinner.NumberEditor(jSpINSSProprio_Terc, "0.00"));

        jSpBaseINSS_Terc.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jSpBaseINSS_Terc.setEditor(new javax.swing.JSpinner.NumberEditor(jSpBaseINSS_Terc, "0.00"));

        jLabel17.setText("%");

        jLabel18.setText("%");

        jLabel19.setText("%");

        jLabel20.setText("%");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jSpBaseINSS_Terc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jSpINSSProprio_Terc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jSpINSSPatronal_Terc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jSpINSSTerc_Terc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jSpBaseINSS_Terc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jSpINSSProprio_Terc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jSpINSSPatronal_Terc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jSpINSSTerc_Terc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("IRRF Terceiros"));

        jLabel29.setText("Base de Cálculo");

        jSpBase_IRRFTerc.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jSpBase_IRRFTerc.setEditor(new javax.swing.JSpinner.NumberEditor(jSpBase_IRRFTerc, "0.00"));

        jLabel33.setText("%");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(43, 43, 43)
                .addComponent(jSpBase_IRRFTerc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jSpBase_IRRFTerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("IRRF Cooperado"));

        jLabel37.setText("Base de Cálculo");

        jSpBaseIRRF_Coop.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jSpBaseIRRF_Coop.setEditor(new javax.swing.JSpinner.NumberEditor(jSpBaseIRRF_Coop, "0.00"));

        jLabel41.setText("%");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addGap(43, 43, 43)
                .addComponent(jSpBaseIRRF_Coop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jSpBaseIRRF_Coop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cálculos", jPanel2);

        jCbInteg_Financ.setText("Integração Automática");
        jCbInteg_Financ.setToolTipText("Marcar esta opção fará com que o RPA seja lançado automaticamente no contas a pagar.");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Contas Contábeis"));

        jLabel21.setText("Custo Cooperado");

        jTxtCtaCoop.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel22.setText("Custo terceiros");

        jTxtCtaTerc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel23.setText("INSS/Terceiros");

        jTxtCtaINSS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel24.setText("IRRF");

        jTxtCtaIRRF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel27.setText("Outras despesas");

        jTxtCtaOutras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCtaCoop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCtaINSS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCtaIRRF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtCtaTerc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtCtaOutras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTxtCtaCoop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jTxtCtaTerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(jTxtCtaOutras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jTxtCtaINSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTxtCtaIRRF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel28.setText("Último RPA integrado");

        jTxtUltRpaInteg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtUltRpaInteg.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCbInteg_Financ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtUltRpaInteg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbInteg_Financ)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(jTxtUltRpaInteg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Financeiro", jPanel3);

        jCbInteg_Folha.setText("Integração Automática");
        jCbInteg_Folha.setToolTipText("Marcar esta opção fará com que o RPA seja lançado automaticamente no contas a pagar.");

        jCbTabINSS.setText("Utiliza tabela de INSS local");
        jCbTabINSS.setToolTipText("Marcar esta opção buscará a tabela de INSS da Folha para definir o teto de desconto.");

        jCbTabIRRF.setText("Utiliza tabela de IRRF local");
        jCbTabIRRF.setToolTipText("Marcar esta opção buscará a tabela de IRRF da Folha para definir a alíquota de desconto.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCbInteg_Folha)
                    .addComponent(jCbTabINSS)
                    .addComponent(jCbTabIRRF))
                .addContainerGap(350, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbInteg_Folha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbTabINSS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbTabIRRF)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Folha", jPanel4);

        jLabel25.setText("Última sincronização");

        jTxtSinc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtSinc.setEnabled(false);

        jLabel26.setText("Último usuário ");

        jTxtUser.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtUser.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(jTxtSinc))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTxtSinc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(294, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sincronização", jPanel5);

        jBtnGravar.setText("Gravar");
        jBtnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGravarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGravar)
                    .addComponent(jBtnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGravarActionPerformed
        salvaDefault();
    }//GEN-LAST:event_jBtnGravarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnGravar;
    private javax.swing.JCheckBox jCbInteg_Financ;
    private javax.swing.JCheckBox jCbInteg_Folha;
    private javax.swing.JCheckBox jCbMargemVar;
    private javax.swing.JCheckBox jCbPedagio;
    private javax.swing.JCheckBox jCbTabINSS;
    private javax.swing.JCheckBox jCbTabIRRF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSpinner jSpBaseINSS_Terc;
    private javax.swing.JSpinner jSpBaseIRRF_Coop;
    private javax.swing.JSpinner jSpBase_IRRFTerc;
    private javax.swing.JSpinner jSpINSSPatronal_Terc;
    private javax.swing.JSpinner jSpINSSProprio_Terc;
    private javax.swing.JSpinner jSpINSSTerc_Terc;
    private javax.swing.JSpinner jSpInssAliq_Coop;
    private javax.swing.JSpinner jSpInssBase_Coop;
    private javax.swing.JSpinner jSpInssPatronal_Coop;
    private javax.swing.JSpinner jSpInssTerc_Coop;
    private javax.swing.JSpinner jSpMargemCoop;
    private javax.swing.JSpinner jSpMargemTerc;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTxtCtaCoop;
    private javax.swing.JTextField jTxtCtaINSS;
    private javax.swing.JTextField jTxtCtaIRRF;
    private javax.swing.JTextField jTxtCtaOutras;
    private javax.swing.JTextField jTxtCtaTerc;
    private javax.swing.JTextField jTxtSinc;
    private javax.swing.JTextField jTxtUltRpaInteg;
    private javax.swing.JTextField jTxtUser;
    // End of variables declaration//GEN-END:variables

    private void buscaDefault() {
        cd.carregaProp();

        jTxtSinc.setText(df.format(cd.getUltima_sincronizacao()));
        jTxtUser.setText(cd.getUlt_user());

        jSpMargemTerc.setValue(cd.getMargem_terceiro() * 100.00);
        jSpMargemCoop.setValue(cd.getMargem_cooperado() * 100.00);
        jSpInssBase_Coop.setValue(cd.getInss_bc_cooperado() * 100.00);
        jSpInssAliq_Coop.setValue(cd.getInss_aliq_cooperado() * 100.00);
        jSpInssPatronal_Coop.setValue(cd.getInss_aliq_patronal_cooperado() * 100.00);
        jSpInssTerc_Coop.setValue(cd.getCoop_terceiros_aliq() * 100.00);

        jSpBaseINSS_Terc.setValue(cd.getInss_bc_terceiro() * 100.00);
        jSpINSSProprio_Terc.setValue(cd.getInss_aliq_terceiro() * 100.00);
        jSpINSSPatronal_Terc.setValue(cd.getInss_aliq_patronal_terceiro() * 100.00);
        jSpINSSTerc_Terc.setValue(cd.getTerc_terceiros_aliq() * 100.00);

        jSpBaseIRRF_Coop.setValue(cd.getIrrf_bc_cooperado() * 100.00);
        jSpBase_IRRFTerc.setValue(cd.getIrrf_bc_terceiro() * 100.00);

        jTxtCtaCoop.setText(cd.getCta_cooperado());
        jTxtCtaTerc.setText(cd.getCta_terceiro());
        jTxtCtaINSS.setText(cd.getCta_inss());
        jTxtCtaIRRF.setText(cd.getCta_irrf());
        jTxtCtaOutras.setText(cd.getCta_outras_despesas());
        jTxtUltRpaInteg.setText(cd.getUlt_integ_fin());
        
        //INTEGRAR COM O FINANCEIRO
        jCbInteg_Financ.setSelected(cd.getLanca_fin());
        
        //INTEGRAR COM A FOLHA DE PAGAMENTOS
        jCbInteg_Folha.setSelected(cd.getLanca_folha());

        //CALCULAR COM MARGEM VARIÁVEL
        jCbMargemVar.setSelected(cd.getMargem_variavel());

        //UTILIZAR TABELA INSS FOLHA
        jCbTabINSS.setSelected(cd.getInss_tab_local());
        
        //UTILIZAR TABELA IRRF FOLHA
        jCbTabIRRF.setSelected(cd.getIrrf_tab_local());
        
        //CONSIDERAR PEDÁGIO NO CÁLCULO
        jCbPedagio.setSelected(cd.getConsidera_pedagio());

    }

    private void salvaDefault() {
        inss_aliq_cooperado = Double.parseDouble(jSpInssAliq_Coop.getValue().toString());
        inss_aliq_patronal_cooperado = Double.parseDouble(jSpInssPatronal_Coop.getValue().toString());
        inss_aliq_patronal_terceiro = Double.parseDouble(jSpINSSPatronal_Terc.getValue().toString());
        inss_aliq_terceiro = Double.parseDouble(jSpINSSProprio_Terc.getValue().toString());
        inss_bc_cooperado = Double.parseDouble(jSpInssBase_Coop.getValue().toString());
        inss_bc_terceiro = Double.parseDouble(jSpBaseINSS_Terc.getValue().toString());
        irrf_bc_cooperado = Double.parseDouble(jSpBaseIRRF_Coop.getValue().toString());
        irrf_bc_terceiro = Double.parseDouble(jSpBase_IRRFTerc.getValue().toString());
        margem_cooperado = Double.parseDouble(jSpMargemCoop.getValue().toString());
        margem_terceiro = Double.parseDouble(jSpMargemTerc.getValue().toString());
        coop_terceiros_aliq = Double.parseDouble(jSpInssTerc_Coop.getValue().toString());
        terc_terceiros_aliq = Double.parseDouble(jSpINSSTerc_Terc.getValue().toString());
        cta_cooperado = jTxtCtaCoop.getText();
        cta_terceiro = jTxtCtaTerc.getText();
        cta_outras_despesas = jTxtCtaOutras.getText();
        cta_inss = jTxtCtaINSS.getText();
        cta_irrf = jTxtCtaIRRF.getText();
        ult_integ_fin = jTxtUltRpaInteg.getText();
        considera_pedagio = jCbPedagio.isSelected();
        inss_tab_local = jCbTabINSS.isSelected();
        irrf_tab_local = jCbTabIRRF.isSelected();
        lanca_fin = jCbInteg_Financ.isSelected();
        lanca_folha = jCbInteg_Folha.isSelected();
        margem_variavel = jCbMargemVar.isSelected();
        
        cd.setCoop_terceiros_aliq(coop_terceiros_aliq / 100.00);
        cd.setCta_cooperado(cta_cooperado);
        cd.setCta_inss(cta_inss);
        cd.setCta_irrf(cta_irrf);
        cd.setCta_outras_despesas(cta_outras_despesas);
        cd.setCta_terceiro(cta_terceiro);
        cd.setInss_aliq_cooperado(inss_aliq_cooperado / 100.00);
        cd.setInss_aliq_patronal_cooperado(inss_aliq_patronal_cooperado / 100.00);
        cd.setInss_aliq_patronal_terceiro(inss_aliq_patronal_terceiro / 100.00);
        cd.setInss_aliq_terceiro(inss_aliq_terceiro / 100.00);
        cd.setInss_bc_cooperado(inss_bc_cooperado / 100.00);
        cd.setInss_bc_terceiro(inss_bc_terceiro / 100.00);
        cd.setInss_tab_local(inss_tab_local);
        cd.setIrrf_bc_cooperado(irrf_bc_cooperado / 100.00);
        cd.setIrrf_bc_terceiro(irrf_bc_terceiro / 100.00);
        cd.setIrrf_tab_local(irrf_tab_local);
        cd.setLanca_fin(lanca_fin);
        cd.setLanca_folha(lanca_folha);
        cd.setMargem_cooperado(margem_cooperado / 100.00);
        cd.setMargem_terceiro(margem_terceiro / 100.00);
        cd.setMargem_variavel(margem_variavel);
        cd.setTerc_terceiros_aliq(terc_terceiros_aliq / 100.00);
        cd.setConsidera_pedagio(considera_pedagio);

        if (cd.salvaProp()) {
            JOptionPane.showMessageDialog(this, "Parâmetros atualizados.");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível atualizar todos os parâmetros.");
        }

    }
}
