/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telaCadastros;

import conexoes.ConexaoFB;
import conexoes.ConexaoMySQL;
import conexoes.ConexaoORCL;
import ferramentas.DataFechamento;
import ferramentas.JNumberFormatField99;
import ferramentas.ManipulaData;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ferna
 */
public class UtilResumo extends javax.swing.JInternalFrame {

    private int usu_inc;
    private final conexoes.ConexaoMySQL cn = new ConexaoMySQL();
    private final conexoes.ConexaoORCL cnor = new ConexaoORCL();
    private final DateFormat dateOut = new SimpleDateFormat("yyyy/MM/dd");
    private final DateFormat dateIn = new SimpleDateFormat("dd/MM/yyyy");
    private final DateFormat dateFb = new SimpleDateFormat("dd.MM.yyyy HH:mm");
    private final DecimalFormat df = new DecimalFormat("#,##0.00");
    private conexoes.ConexaoFB cnfb;

    //private Timestamp
    /**
     * Creates new form UtilResumo
     */
    public UtilResumo(int user) {
        initComponents();
        System.out.println("Usuário recebido pelo UtilResumo: " + user);
        this.usu_inc = user;
        this.cnfb = new ConexaoFB(usu_inc);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/####");
            jTxtCompetencia = new javax.swing.JFormattedTextField(data);
            jButton1 = new javax.swing.JButton();
            jCheckBox1 = new javax.swing.JCheckBox();
            jCheckBox2 = new javax.swing.JCheckBox();
            jCheckBox3 = new javax.swing.JCheckBox();
            jPanel2 = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            jTxtLocalLiquido = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtLocalIRRF = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtLocalTerceiros = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtLocalINSS = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtLocalBruto = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtLocalQuantidade = new javax.swing.JTextField();
            jTxtStatusLocal = new javax.swing.JTextField();
            jPanel3 = new javax.swing.JPanel();
            jLabel9 = new javax.swing.JLabel();
            jLabel10 = new javax.swing.JLabel();
            jLabel11 = new javax.swing.JLabel();
            jLabel12 = new javax.swing.JLabel();
            jLabel13 = new javax.swing.JLabel();
            jLabel14 = new javax.swing.JLabel();
            jLabel15 = new javax.swing.JLabel();
            jTxtFinanceiroLiquido = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtFinanceiroIRRF = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtFinanceiroTerceiros = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtFinanceiroINSS = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtFinanceiroBruto = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtFinanceiroQuantidade = new javax.swing.JTextField();
            jTxtFinanceiroStatus = new javax.swing.JTextField();
            jPanel4 = new javax.swing.JPanel();
            jLabel16 = new javax.swing.JLabel();
            jLabel17 = new javax.swing.JLabel();
            jLabel18 = new javax.swing.JLabel();
            jLabel19 = new javax.swing.JLabel();
            jLabel20 = new javax.swing.JLabel();
            jLabel21 = new javax.swing.JLabel();
            jLabel22 = new javax.swing.JLabel();
            jTxtFolhaLiquido = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtFolhaIRRF = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtFolhaTerceiros = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtFolhaINSS = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtFolhaBruto = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jTxtFolhaQuantidade = new javax.swing.JTextField();
            jTxtFolhaStatus = new javax.swing.JTextField();

            setClosable(true);
            setTitle("Resumo da integração");

            jLabel1.setText("Competência");

        }
        catch (Exception e){
        }

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Local");

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Financeiro");

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Folha de Pagamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jTxtCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1)
                .addComponent(jCheckBox1)
                .addComponent(jCheckBox2)
                .addComponent(jCheckBox3))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Recibos do período"));

        jLabel2.setText("Quantidade");

        jLabel3.setText("Valor Bruto");

        jLabel4.setText("INSS");

        jLabel5.setText("Terceiros");

        jLabel6.setText("IRRF");

        jLabel7.setText("Valor Líquido");

        jLabel8.setText("Status");

        jTxtLocalLiquido.setEnabled(false);

        jTxtLocalIRRF.setEnabled(false);

        jTxtLocalTerceiros.setEnabled(false);

        jTxtLocalINSS.setEnabled(false);

        jTxtLocalBruto.setEnabled(false);

        jTxtLocalQuantidade.setEnabled(false);

        jTxtStatusLocal.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTxtStatusLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtLocalQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtLocalBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtLocalINSS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtLocalTerceiros, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtLocalIRRF, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtLocalLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtLocalQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtLocalBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtLocalINSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtLocalTerceiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtLocalIRRF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtLocalLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtStatusLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lançamentos no Financeiro"));

        jLabel9.setText("Quantidade");

        jLabel10.setText("Valor Bruto");

        jLabel11.setText("INSS");

        jLabel12.setText("Terceiros");

        jLabel13.setText("IRRF");

        jLabel14.setText("Valor Líquido");

        jLabel15.setText("Status");

        jTxtFinanceiroLiquido.setEnabled(false);

        jTxtFinanceiroIRRF.setEnabled(false);

        jTxtFinanceiroTerceiros.setEnabled(false);

        jTxtFinanceiroINSS.setEnabled(false);

        jTxtFinanceiroBruto.setEnabled(false);

        jTxtFinanceiroQuantidade.setEnabled(false);

        jTxtFinanceiroStatus.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTxtFinanceiroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFinanceiroQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFinanceiroBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFinanceiroINSS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFinanceiroTerceiros, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFinanceiroIRRF, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtFinanceiroLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtFinanceiroQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtFinanceiroBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTxtFinanceiroINSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTxtFinanceiroTerceiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTxtFinanceiroIRRF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTxtFinanceiroLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTxtFinanceiroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Lançamentos na Folha"));

        jLabel16.setText("Quantidade");

        jLabel17.setText("Valor Bruto");

        jLabel18.setText("INSS");

        jLabel19.setText("Terceiros");

        jLabel20.setText("IRRF");

        jLabel21.setText("Valor Líquido");

        jLabel22.setText("Status");

        jTxtFolhaLiquido.setEnabled(false);

        jTxtFolhaIRRF.setEnabled(false);

        jTxtFolhaTerceiros.setEnabled(false);

        jTxtFolhaINSS.setEnabled(false);

        jTxtFolhaBruto.setEnabled(false);

        jTxtFolhaQuantidade.setEnabled(false);

        jTxtFolhaStatus.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTxtFolhaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFolhaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFolhaBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFolhaINSS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFolhaTerceiros, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFolhaIRRF, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtFolhaLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTxtFolhaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTxtFolhaBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTxtFolhaINSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTxtFolhaTerceiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTxtFolhaIRRF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTxtFolhaLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTxtFolhaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTxtCompetencia.getText().length() == 7) {

            defineStatus();
        } else {
            JOptionPane.showMessageDialog(this, "Competência não informada.", "Resumo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTxtCompetencia;
    private javax.swing.JTextField jTxtFinanceiroBruto;
    private javax.swing.JTextField jTxtFinanceiroINSS;
    private javax.swing.JTextField jTxtFinanceiroIRRF;
    private javax.swing.JTextField jTxtFinanceiroLiquido;
    private javax.swing.JTextField jTxtFinanceiroQuantidade;
    private javax.swing.JTextField jTxtFinanceiroStatus;
    private javax.swing.JTextField jTxtFinanceiroTerceiros;
    private javax.swing.JTextField jTxtFolhaBruto;
    private javax.swing.JTextField jTxtFolhaINSS;
    private javax.swing.JTextField jTxtFolhaIRRF;
    private javax.swing.JTextField jTxtFolhaLiquido;
    private javax.swing.JTextField jTxtFolhaQuantidade;
    private javax.swing.JTextField jTxtFolhaStatus;
    private javax.swing.JTextField jTxtFolhaTerceiros;
    private javax.swing.JTextField jTxtLocalBruto;
    private javax.swing.JTextField jTxtLocalINSS;
    private javax.swing.JTextField jTxtLocalIRRF;
    private javax.swing.JTextField jTxtLocalLiquido;
    private javax.swing.JTextField jTxtLocalQuantidade;
    private javax.swing.JTextField jTxtLocalTerceiros;
    private javax.swing.JTextField jTxtStatusLocal;
    // End of variables declaration//GEN-END:variables

    private void defineStatus() {

        boolean resposta;

        Double liquido1 = 0.00;
        Double liquido2 = 0.00;

        //VERIFICA QUE SE EXISTE ALGUMA PESQUISA SELECIONADA
        if (jCheckBox1.isSelected() | jCheckBox2.isSelected() | jCheckBox3.isSelected()) {
            String sql;
            ManipulaData dm = new ManipulaData();

            Date competencia = dm.ultimoDia(jTxtCompetencia.getText());

            //PESQUISA O STATUS DOS CONHECIMENTOS LOCAIS
            if (jCheckBox1.isSelected()) {

                DataFechamento fechamento = new DataFechamento();
                resposta = fechamento.verificaFechamento(jTxtCompetencia.getText());

                //DEFINE A MENSAGEM DO STATUS
                if (resposta) {
                    jTxtStatusLocal.setText("Concluído");
                } else {
                    jTxtStatusLocal.setText("Aberto");
                }

                //SOMA OS VALORES NO BANCO DE DADOS
                sql = "SELECT count(codigo) as quantidade, "
                        + "sum(vlr_bruto) as bruto, sum(inss) as inss, "
                        + "sum(terceiros) as terceiros, sum(irrf) as irrf, "
                        + "sum(liquido) as liquido FROM rpa "
                        + "WHERE month(emissao) = month('" + dateOut.format(competencia) + "')"
                        + "AND year(emissao) = year('" + dateOut.format(competencia) + "');";

                if (cn.conecta()) {
                    try {
                        if (cn.executeConsulta(sql)) {
                            while (cn.rs.next()) {
                                jTxtLocalQuantidade.setText(cn.rs.getString("quantidade"));
                                jTxtLocalBruto.setText(df.format(cn.rs.getDouble("bruto")));
                                jTxtLocalINSS.setText(df.format(cn.rs.getDouble("inss")));
                                jTxtLocalIRRF.setText(df.format(cn.rs.getDouble("irrf")));
                                jTxtLocalLiquido.setText(df.format(cn.rs.getDouble("liquido")));
                                jTxtLocalTerceiros.setText(df.format(cn.rs.getDouble("terceiros")));
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Consulta local não realizada", "Resumo", JOptionPane.WARNING_MESSAGE);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Não foi possível verificar o resumo local.\n" + e, "Resumo", JOptionPane.ERROR_MESSAGE);
                    } finally {
                        cn.desconecta();
                    }
                }
            }

            System.out.println("Definindo valor líquido2.");
            liquido2 = Double.parseDouble(jTxtLocalLiquido.getText().replace(".", "").replace(",", "."));

            //PESQUISA O STATUS DOS CONHECIMENTOS NO FINANCEIRO
            if (jCheckBox2.isSelected()) {
                sql = "with contagem as ( "
                        + "select count(a.codigo) as quantidade, "
                        + "sum(b.valor) as bruto, "
                        + "sum(c.valor) as INSS, "
                        + "sum(d.valor) as irrf "
                        + "FROM fin_contas_pagar a "
                        + "LEFT JOIN fin_contas_pagar_detalhe b on (b.empresa = a.empresa and b.codigo = a.codigo and (b.planoconta = 2786 or b.planoconta = 2789 or b.planoconta = 479)) "
                        + "LEFT JOIN fin_contas_pagar_detalhe c on (c.empresa = a.empresa and c.codigo = a.codigo and c.planoconta = 258) "
                        + "LEFT JOIN fin_contas_pagar_detalhe d on (d.empresa = a.empresa and d.codigo = a.codigo and d.planoconta = 240) "
                        + "WHERE a.tipodoc = 25 and extract(month from a.dt_emissao) = " + (competencia.getMonth() + 1) + " "
                        + "AND extract(year from a.dt_emissao) = " + (competencia.getYear() + 1900) + " ) "
                        + "SELECT quantidade,bruto,inss,irrf, "
                        + "bruto - case when inss is null then 0.00 else inss end - case when irrf is null then 0.00 else irrf end as liquido "
                        + "FROM contagem ;";

                
                if (cnfb.conecta()) {
                    try {
                        cnfb.executeConsulta(sql);
                        while (cnfb.rs.next()) {
                            jTxtFinanceiroQuantidade.setText(cnfb.rs.getString("quantidade"));
                            jTxtFinanceiroBruto.setText(df.format(cnfb.rs.getDouble("bruto")));
                            jTxtFinanceiroINSS.setText(df.format(cnfb.rs.getDouble("inss")));
                            jTxtFinanceiroIRRF.setText(df.format(cnfb.rs.getDouble("irrf")));
                            jTxtFinanceiroLiquido.setText(df.format(cnfb.rs.getDouble("liquido")));
                            liquido1 = cnfb.rs.getDouble("liquido");
                            //jTxtFinanceiroTerceiros.setText(df.format(cnfb.rs.getDouble("terceiros")));
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Não foi possível verificar o resumo do financeiro.\n" + e, "Resumo", JOptionPane.ERROR_MESSAGE);
                    } finally {
                        cnfb.desconecta();
                    }
                }

                if ((liquido1 - liquido2) > -1.00 && (liquido1 - liquido2) < 1.00) {
                    jTxtFinanceiroStatus.setText("Concluído");
                } else {
                    jTxtFinanceiroStatus.setText("Aberto");
                }
            }

            //PESQUISA O STATUS DOS CONHECIMENTOS NA FOLHA DE PAGAMENTOS.
            if (jCheckBox3.isSelected()) {
                sql = "Select count(a.seqpte) as quantidade, "
                        + "sum(a.renbru) as bruto, "
                        + "sum(a.conins) as inss, "
                        + "sum(a.instrp) as terceiros, "
                        + "sum(a.IRFRET) as IRRF, "
                        + "sum(a.valliq) as liquido "
                        + "from r032tpg a "
                        + "where a.CMPPTE = '01/" + jTxtCompetencia.getText() + "' "
                        + "and a.numemp = 7";

                if (cnor.conecta()) {
                    try {
                        cnor.executeConsulta(sql);
                        while (cnor.rs.next()) {
                            jTxtFolhaQuantidade.setText(cnor.rs.getString("quantidade"));
                            jTxtFolhaBruto.setText(df.format(cnor.rs.getDouble("bruto")));
                            jTxtFolhaINSS.setText(df.format(cnor.rs.getDouble("inss")));
                            jTxtFolhaIRRF.setText(df.format(cnor.rs.getDouble("irrf")));
                            jTxtFolhaLiquido.setText(df.format(cnor.rs.getDouble("liquido")));
                            jTxtFolhaTerceiros.setText(df.format(cnor.rs.getDouble("terceiros")));
                            liquido1 = cnor.rs.getDouble("liquido");
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Não foi possível verificar o resumo da Folha de Pagamentos.\n" + e, "Resumo", JOptionPane.ERROR_MESSAGE);
                    } finally {
                        cnor.desconecta();
                    }
                }
                
                if ((liquido1 - liquido2) > -1.00 && (liquido1 - liquido2) < 1.00) {
                    jTxtFolhaStatus.setText("Concluído");
                } else {
                    jTxtFolhaStatus.setText("Aberto");
                }

            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione ao menos um resumo para continuar.", "Resumo", JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
